### ISSUE TITLE
Understanding Mockpass Integration with SimpleSamlPhp

### ISSUE THREAD

**Issue by pojie0310** [opengovsg/mockpass#15]
Hi all, 

Thank for all your products that you have developed.
which is really a good help for us developers.
We currently have a system that is trying to communicate with Singpass.
Base on our understanding on how Singpass onboard clients.
We are required to give Singpass metadata.
Can we find out from your team on how we can set up the metadata on mockpass.
So we can do a end to end testing.

Hope to hear from you soon.

Thanks.

**Comment by LoneRifle** [comment]
Hi @pojie0310 , and thanks for getting in touch! Because MockPass is only intended to (badly) mimic SingPass, there will be no need for metadata setup. You will however need to figure out how to configure your application to make use of the certs and associated keys found at `static/certs/`.

Alternatively, you can inject the paths to your cert and public key into mockpass using the following environment variables):
https://github.com/opengovsg/mockpass/blob/367c252053fe93dfbbf02d8ddbe1073c656cc376/index.js#L13-L16

This is information that you can find in the README too.

**Comment by pojie0310** [comment]
Is there a way for us to know in mockpass, that it receives a SAMLart from our end? Base on the README file, you have this part. http://localhost:5156/singpass/soap (receives SAML artifact and returns assertion) this means it is coming from my application correct? 

And this command needs to point to my application that is suppose to receive the SAML from mockpass correct?
$ export SINGPASS_ASSERT_ENDPOINT= http://localhost:5000/singpass/assert {change to my application url}

**Comment by LoneRifle** [comment]
By and large correct

**Comment by pojie0310** [comment]
Thank you for the help. I think we understood a bit on what went wrong on our side.
